/**
 * Created by Jesse White on 2/25/15
 * Assignment: Functions
 */

// This function should randomly pick two numbers
// then concatenate them into a new number as a string
// and convert that string number into a number type,
// then repeat the above process 6 times
function floridaLotto(u) {

    var lottoNums = []; // array to place the random lottery numbers in
    var selectList = ["1", "2", "3", "4", "5", "6", "7", "8", "9"]; // list of string numbers to select
    var selectNum1; // first number to store
    var selectNum2; // second number to store
    var storeNum;   // string number to store
    var i = 0;      // indexing number to increment
    var invalid = console.log("I didn't understand that."); // invalid statement to display if u does not equal F or f
    // IF u equals F or f
    if(u == "F" || u == "f") {
        // execute this while loop
        while(lottoNums.length <= 4) {                              // while lottoNums length is less than or equal to 4
            selectNum1 = Math.floor(Math.random() * 9);                 // gets a random whole number
            selectNum2 = Math.floor(Math.random() * 9);                 // gets a random whole number
            storeNum = selectList[selectNum1] + selectList[selectNum2]; // concatenates the two randomly selected string numbers
            lottoNums[i] = Number(storeNum);                            // places the concatenated string as a number
            i++;                                                        // increases the storing int by one
        }
        // returns the array generated by the while loop
        return lottoNums;

    } else if (u != "F" || u != "f") {
        return invalid; // returns the invalid string
    }

}

// Sets up the variables
var lottoNumbers;
var userIn = prompt("What lottery numbers would you like? " +
    "The Florida lottery or the Powerball?\n\n\t\t\t(Type \"F\"" +
    " for Florida or \"P\" for the Powerball.)");

// Validates the user input
while(userIn == "") {
    userIn = prompt("What lottery numbers would you like? " +
    "The Florida lottery or the Powerball?\n\n\t\t\t(Type \"F\"" +
    " for Florida or \"P\" for the Powerball.)");
}

lottoNumbers = floridaLotto(userIn);

console.log(lottoNumbers);

/*
function powerball(n) {

}

if(userIn == "P" || userIn == "p") {
    powerball();
}
*/